name: bubble_chart
description:
  A simple Dart implementation of bubble chart.
  It creates bubbles in random points and collide its all to container center.
  Can be implemented with any features.
version: 0.2.0
author: Lorenzo Pongetti <lorenzo.pongetti@gmail.com>

homepage: https://github.com/lpongetti/bubble_chart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter